### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by yrcrcy** [ashish-kubade/AFN#1]
Thank you for your contribution. Can you write the implementation steps in a READme.txt file? For example, how to train and verify, there is no description of the document feel read very laborious, thank you!

**Comment by ashish-kubade** [comment]
We have added the READme.m. with instructions to train and test. Hope that helps.

**Comment by ashj9** [comment]
> Thank you for your contribution. Can you write the implementation steps in a READme.txt file? For example, how to train and verify, there is no description of the document feel read very laborious, thank you!

**Comment by yrcrcy** [comment]
Thanks.
