### ISSUE TITLE
The link of pretrained model doesn't work

### ISSUE THREAD

**Issue by djx99** [ashish-kubade/AFN#2]
Hi, Thanks for your work, but the link of pretrained model doesn't work

**Comment by ashish-kubade** [comment]
Hi @djx99, thanks for letting me know. It seems there has been a directory structure change in my gdrive. I will share the updated link in a couple of days. Sorry for the inconvenience.

**Comment by djx99** [comment]
Thanks for the quick reply, I'm in a bit of a hurry, can you email it to me ASAP? Thank you again
2540204751@qq.com

**Comment by ashish-kubade** [comment]
Hi @djx99, the checkpoint links have been correctly updated now. Sorry for the inconvenience caused.
